config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  resources :posts
  
  devise_for :users
  
  get 'pages/post'
  get 'pages/resources'
  get 'pages/contact'

   

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def blog
  end

  def resources
  end

  def contact
  end
  
  def course features
  end
  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<footer>
  <div class="container">
    <div class="row">
    <div class="col-xs-3">
      <p><a href="/"><%= image_tag "logo.png" %></a></p>
    </div>
    <div class="col-xs-6">
      <nav>
        <ul class="list-unstyled list-inline">
          <li><%= link_to "Home", root_path, class: "ft-link" %></li>
          <li><%= link_to "Blog", posts_path, class: "ft-link" %></li>
          <li><%= link_to "Resources", pages_resources_path, class: "ft-link" %></li>
          <li><%= link_to "Contact", pages_contact_path, class: "ft-link" %></li>
          <li><%= link_to "Sign up now", root_path, class: "signup-link" %></li>
        </ul>
      </nav>
    </div>
    <div class="col-xs-3">
      <p class="pull-right">&copy; 2014 Brad Hussey</p>
    </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<header class="site-header" role="banner">
<!--   NAVBAR -->
  <div class="navbar-wrapper">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
<!--           LOGO PlACEMENT REPLACE "LOGO IMAGE W <img src=""> -->
          <a class="navbar-brand" href="/"><%= image_tag "logo.png" %></a>
        </div>
<!--           NAVBAR COLLAPSE -->
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><%= link_to "Home", root_path %></li>
              <li><%= link_to "Blog", posts_path %></li>
              <li><%= link_to "Resources", pages_resources_path %></li>
              <li><%= link_to "Contact", pages_contact_path %></li>
              <% if current_user %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              <% else %>
              <li><%= link_to "Log In", new_user_session_path, method: :get %></li>
              <li><%= link_to "Sign Up", new_user_registration_path, method: :get %></li>
              <% end %>
            </ul>            
          </div>
          
        
      </div>
    </div>
  </div>
</header>

app/views/layouts/_modal.html.erb
<!-- MODAL -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          <i class="fa fa-envelope"></i> Subscribe to our mailing list
        </h4>
        
      </div>
      
      <div class="modal-body">
        <p>Simply enter your name and email. As a thank you for joining us, we're going to give you one of our best-selling courses, <em> for free!</em></p>
      
        <form class="form-inline" role="form">
          <div class="form-group">
            <label class="sr-only" for="subscribe-name">Your first name</label>
            <input type="text" class="form-control" id="subscribe-name" placeholder="Your first name">
          </div>
           
          <div class="form-group">
            <label class="sr-only" for="subscribe-email">Your email</label>
            <input type="text" class="form-control" id="subscribe-email" placeholder="Your email">
          </div>
          
            <input type="submit" class="btn btn-danger" value="Subscribe!">  
        </form>
      
        <hr>
        
        <p><small>By providing your email you consent to receiving occasional promotional emails &amp; newsletters. <br>No Spam. Just good stuff. We respect your privacy &amp; you may unsubscribe at any time. We will never give your email address out to anyone.</small></p>
      </div> <!-- MODAL BODY -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WpTheme</title>
 
  <%= csrf_meta_tags %>
  
  <!--   BOOTSTRAP CORE CSS -->
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
<!--   FONT AWESOME ICONS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  
<!--   GOOGLE FONTS -->
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  
<!--   CUSTOM CSS -->
  <link href="assets/css/custom.css" rel="stylesheet">
 
</head>
<body>
  
  
  
  <%= render 'layouts/header' %>
  
  <% unless notice.nil? %>
  <div class="app-alert">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
          </button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <% end %>
  

  <div class="wrapper">
    <%= yield %>
  </div>  

  <%= render 'layouts/modal' %>
  
  <%= render 'layouts/footer' %>
  
  <!--   TYPEKIT -->
<script src="//use.typekit.net/cuf6dza.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
  
    <!-- BOOTSTRAP CORE JAVASCRIPT -->
<!-- include javascript, jQuery FIRST -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/resources.html.erb
<h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="blog">

  <section class="feature-image feature-image-default-alt" data-type="background" data-speed="2">  
    <h1 class="page-title">Blog</h1>  
  </section>
  
<!--   ==== BLOG CONTENT ==== -->
  
  <div class="container">
    <div class="row" id="primary">
      
      <main id="content" class="col-sm-8" role="main">
        
        <% @posts.each do |post| %>
        <article class="post">
          <header>
            <h3><%= link_to "#{post.title}", post_path(post) %></h3>
            <div class="post-details">
              <i class="fa fa-user"></i><%= " #{post.user.first_name.capitalize} #{post.user.last_name.capitalize[0]}." %>
              <i class="fa fa-clock-o"></i><%= (post.created_at).strftime(" %b %d, %Y") %>
              <i class="fa fa-folder"></i><a href=""> Tutorials</a>, <a href="">Coding</a>
              <i class="fa fa-tags"></i> Tagged <a href="">wordpress</a>, <a href="">premium</a>, <a href="">another tag</a>, <a href="">yadda yadaa</a>
              
              <div class="post-comments-badge">
                <a href=""><i class="fa fa-comments"></i>168</a>
              </div>
            </div> <!-- post details -->
          </header>
          <div class="post-image">
            <%= image_tag "hero-bg.jpg", alt: "Hero image" %>
          </div> <!-- post image -->
          <div class="post-excerpt">
            <p><%= post.body %>... <%= link_to "continue reading &raquo".html_safe, post_path(post), class: "post.html" %></p>
            
            
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            
          </div><!-- post exerpt -->
        </article><!-- post -->
        <% end %>
        
        <% if user_signed_in? %>
           <%= link_to 'New Post', new_post_path %>
        <% end %>
        
      </main>
      
      <!-- SIDEBAR 
      ================================================ -->
      <aside class="col-sm-4">
        <div class="widget">
          <h4>Join our Mailing List</h4>
          <p>keep up-to-date with the latest news, and we'll <strong>send you something special as a thank you!</strong></p>
          <button class="btn btn-success btn-lg btn-blcok" data-toggle="modal" data-target="#myModal">
            Click here to subscribe!
          </button>
        </div><!-- widget -->
        
        <div class="widget">
          <form role="form" class="search-form">
            <label for="sidebar-search" class="sr-only">Search the blog</label>
            <input type="text" id="sidebar-search" placeholder="Search the blog... ">
          </form>
        </div><!-- widget -->
        
        <div class="widget">
          <h4>About Bootstrap to WordPress</h4>
          <p>Art party gastropub locavore, brunch fixie hella whatever slow-carb leggings Neutra crucifix cardigan put a bird on it swag Marfa. Normcore sustainable seitan asymmetrical. Seitan Pitchfork jean shorts, stumptown ethical sriracha fap ugh retro mixtape DIY cliche bespoke disrupt Schlitz. Fap cardigan 3 wolf moon jean shorts chillwave. Salvia wayfarers pickled, four dollar toast Blue Bottle XOXO Shoreditch sriracha slow-carb forage leggings raw denim viral cardigan.</p>
        </div><!-- widget -->
        
        <div class="widget">
          <h4>Recent Posts</h4>
          <ul>
            <li><a href="">Blog post #1</a></li>
            <li><a href="">Blog post #2</a></li>
            <li><a href="">Blog post #3</a></li>
            <li><a href="">Blog post #4</a></li>
            <li><a href="">Blog post #5</a></li>
          </ul>
        </div><!-- widget -->
        
        <div class="widget">
          <h4>Categories</h4>
          <ul>
            <li><a href="">Category #1</a></li>
            <li><a href="">Category #2</a></li>
            <li><a href="">Category #3</a></li>
            <li><a href="">Category #4</a></li>
            <li><a href="">Category #5</a></li>
          </ul>
        </div><!-- widget -->
      </aside>
      
      
    </div><!-- row primary -->
  </div><!-- container -->
     
  
<!-- SIGN UP  -->
  <section id="signup" data-type="background" data-speed="4">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h2>Are you ready to take your coding skills the the <strong>next level </strong>?</h2>
          <p><a href="#" class="btn btn-lg btn-block btn-success">Yes, sign me up!</a></p>
        </div>
      </div>
    </div>  
  </section>
  

  
</div> <!-- end blog -->

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
  <!-- MAIN CONTENT 
================================================== -->
  <div class="container">
    <div class="row primary">
      
      <div id="content" class="col-sm-8">
        <article class="post">
          <header>
            <h1><%= @post.title %></h1>
            <div class="post-details">
              <i class="fa fa-user"></i> Brad Hussey
              <i class="fa fa-clock-o"></i><%= (@post.created_at).strftime(" %b %d, %Y") %>
              <i class="fa fa-folder"></i><a href=""> Tutorials</a>, <a href="">Coding</a>
              <i class="fa fa-tags"></i> Tagged <a href="">wordpress</a>, <a href="">premium</a>, <a href="">another tag</a>, <a href="">yadda yadaa</a>
              
              <div class="post-comments-badge">
                <a href=""><i class="fa fa-comments"></i>168</a>
              </div>
            </div> <!-- post details -->
          </header>
          <div class="post-image">
            <%= image_tag "hero-bg.jpg", alt: "Hero image" %>
          </div> <!-- post image -->
          <div class="post-body">
            
            <p><%= @post.body %></p>
        
          </div><!-- post-body -->
        </article><!-- post -->
        
        <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Back', posts_path %>
      
      
<! COMMENTS
================================================ -->
        <div id="comments">
          <div class="comments-wrap">
            <h3>4 comments</h3>

            <ol class="comments-list">
              <li class="comment">
                <h4>John Smith <small>&bull; Aug 12, 2014</small></h4>
                <div class="comment-body">
                  <p>Art party gastropub locavore, brunch fixie hella whatever slow-carb leggings Neutra crucifix cardigan put a bird on it swag Marfa. Normcore sustainable seitan asymmetrical. Seitan Pitchfork jean shorts, stumptown ethical sriracha fap ugh retro mixtape DIY cliche bespoke disrupt Schlitz. Pitchfork squid authentic, next level scenester distillery lumbersexual polaroid Kickstarter gluten-free. Occupy pop-up you probably haven't heard of them dreamcatcher YOLO, seitan jean shorts Wes Anderson. Fap cardigan 3 wolf moon jean shorts chillwave. Salvia wayfarers pickled, four dollar toast Blue Bottle XOXO Shoreditch sriracha slow-carb forage leggings raw denim viral cardigan.</p>
                </div><!-- comment-body -->

                <ol class="children">
                  <li class="comment">
                    <h4>Chris McCooper <small>&bull; Aug 12, 2014</small></h4>
                    <p>Art party gastropub locavore, brunch fixie hella whatever slow-carb leggings Neutra crucifix cardigan put a bird on it swag Marfa. Normcore sustainable seitan asymmetrical. Seitan Pitchfork jean shorts, stumptown ethical sriracha fap ugh retro mixtape DIY cliche bespoke disrupt Schlitz. Pitchfork squid authentic, next level scenester distillery lumbersexual polaroid Kickstarter gluten-free. Occupy pop-up you probably haven't heard of them dreamcatcher YOLO, seitan jean shorts Wes Anderson. Fap cardigan 3 wolf moon jean shorts chillwave. Salvia wayfarers pickled, four dollar toast Blue Bottle XOXO Shoreditch sriracha slow-carb forage leggings raw denim viral cardigan.</p>

                    <ol class="children">
                      <li class="comment">
                        <h4>Johnny Dee <small>&bull; Aug 14, 2014</small></h4>
                        <p>Occupy pop-up you probably haven't heard of them dreamcatcher YOLO, seitan jean shorts Wes Anderson. Fap cardigan 3 wolf moon jean shorts chillwave. Salvia wayfarers pickled, four dollar toast Blue Bottle XOXO Shoreditch sriracha slow-carb forage leggings raw denim viral cardigan.</p>
                      </li><!-- comment -->
                    </ol><!-- children -->
                  </li><!-- comment -->
                </ol><!-- children -->
              </li><!-- comment -->

              <li class="comment">
                <h4>Jane <small>&bull; Aug 15, 2014</small></h4>
                <p>Occupy pop-up you probably haven't heard of them dreamcatcher YOLO, seitan jean shorts Wes Anderson. Fap cardigan 3 wolf moon jean shorts chillwave. Salvia wayfarers pickled, four dollar toast Blue Bottle XOXO Shoreditch sriracha slow-carb forage leggings raw denim viral cardigan.</p>
              </li><!-- comment -->

            </ol><!-- comments-list -->
            
            <div id="leave-comment">
              <h3>Leave a comment</h3>
              
              <form>
                <p>Your email address will not be published. Required fields are marked <span class="required">*</span></p>
                <p class="comment-form-author">
                  <label for="author">Name *</label>
                  <input type="text" id="author">
                </p>
                <p class="comment-form-author">
                  <label for="email">Email *</label>
                  <input type="email" id="email">
                </p>
                <p class="comment-form-author">
                  <label for="email">Website</label>
                  <input type="url" id="url">
                </p>
                <p class="comment-form-author">
                  <label for="comment">Comment *</label>
                  <textarea id="comment" cols="45" rows="8"></textarea>
                </p>
                <p class="form-submit">
                  <input type="submit" name="submit">
                </p>
              </form>
            </div><!-- leave-comment -->
            
          </div><!-- comments-wrap -->
        </div><!-- comments -->
  
      </div><!-- content col-sm-8 -->
      
      <!-- SIDEBAR 
      ================================================ -->
      <aside class="col-sm-4">
        <div class="widget">
          <h4>Join our Mailing List</h4>
          <p>keep up-to-date with the latest news, and we'll <strong>send you something special as a thank you!</strong></p>
          <button class="btn btn-success btn-lg btn-blcok" data-toggle="modal" data-target="#myModal">
            Click here to subscribe!
          </button>
        </div><!-- widget -->
        
        <div class="widget">
          <form role="form" class="search-form">
            <label for="sidebar-search" class="sr-only">Search the blog</label>
            <input type="text" id="sidebar-search" placeholder="Search the blog... ">
          </form>
        </div><!-- widget -->
        
        <div class="widget">
          <h4>About Bootstrap to WordPress</h4>
          <p>Art party gastropub locavore, brunch fixie hella whatever slow-carb leggings Neutra crucifix cardigan put a bird on it swag Marfa. Normcore sustainable seitan asymmetrical. Seitan Pitchfork jean shorts, stumptown ethical sriracha fap ugh retro mixtape DIY cliche bespoke disrupt Schlitz. Fap cardigan 3 wolf moon jean shorts chillwave. Salvia wayfarers pickled, four dollar toast Blue Bottle XOXO Shoreditch sriracha slow-carb forage leggings raw denim viral cardigan.</p>
        </div><!-- widget -->
        
        <div class="widget">
          <h4>Recent Posts</h4>
          <ul>
            <li><a href="">Blog post #1</a></li>
            <li><a href="">Blog post #2</a></li>
            <li><a href="">Blog post #3</a></li>
            <li><a href="">Blog post #4</a></li>
            <li><a href="">Blog post #5</a></li>
          </ul>
        </div><!-- widget -->
        
        <div class="widget">
          <h4>Categories</h4>
          <ul>
            <li><a href="">Category #1</a></li>
            <li><a href="">Category #2</a></li>
            <li><a href="">Category #3</a></li>
            <li><a href="">Category #4</a></li>
            <li><a href="">Category #5</a></li>
          </ul>
        </div><!-- widget -->
      </aside>
      
      
    </div><!-- row primary -->
  </div><!-- container -->
     
  
<!-- SIGN UP  -->
  <section id="signup" data-type="background" data-speed="4">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h2>Are you ready to take your coding skills the the <strong>next level </strong>?</h2>
          <p><a href="#" class="btn btn-lg btn-block btn-success">Yes, sign me up!</a></p>
        </div>
      </div>
    </div>  
  </section>